name: build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project
        uses: threeal/cmake-action@v2.1.0
